### ISSUE TITLE
hoe deze plugin(s) te installeren in configureren in opencart 3.0.3.6

### ISSUE THREAD

**Issue by huub1972** [dpdconnect/opencart3-shipping#2]
I managed to install DPD parcelservice in opencart 3.0.3.6> In parcelservices i see the following message: DPD Shipping methods are disabled. The current configuration will be ignored. Enable DPD Shipping by changing the status to Enabled.

I can not find DPD shipping methods at all in standard opencart....

**Comment by beireken** [comment]
You should have dpd settings in Extensions > shipping

**Comment by huub1972** [comment]
nee alleen DPD parcelservice, waar komt die settings extentie vandaan? 
![image](https://user-images.githubusercontent.com/61755509/92579951-1e8c2400-f28e-11ea-8abf-30f5df10aece.png)

**Comment by huub1972** [comment]
mogelijk hebben jullie alle nodige files om te installeren? Mogelijk is wat hier in github staat niet voldoende?

**Comment by youri13pixels** [comment]
![2021-03-08_11h57_41](https://user-images.githubusercontent.com/17879045/110312541-83d68d00-8005-11eb-823c-32828b0fb10b.jpg)

Waar kan ik de url vinden?

**Comment by dpdplugin** [comment]
The URL is https://api.dpdconnect.nl
It is important that the plugin is downloaded from the releases page.
